version: '3'
services:
  
  tails-server:
    container_name: tails-server
    build:
      context: ./indy-tails-server
      dockerfile: ./docker/Dockerfile.tails-server 
    ports:
      - 6543:6543
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --log-level debug
        --storage-path /home/indy

  doctor-agent:
    container_name: doctor-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 7000:7000
      - 7080:7080
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --tails-server-base-url http://${ip_address}:6543 
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 7000 
        --inbound-transport ws 0.0.0.0 7001 
        --outbound-transport ws 
        --outbound-transport http 
        --genesis-file /var/lib/indy/my-net/pool_transactions_genesis 
        --log-level info
        --seed 000000000000000000000000Steward3
        --wallet-type indy 
        --wallet-key StewardWallet3 
        --wallet-name StewardWallet3
        --admin-insecure-mode 
        --admin 0.0.0.0 7080 
        -e http://${ip_address}:7000/ 
        -l Doctor
    volumes:
      - /Users/chef/MA/e-Prescriptions/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis

  pharmacy-agent:
    container_name: pharmacy-agent
    build:
      context: ./aries-cloudagent-python
      dockerfile: ./docker/Dockerfile.run
    ports:
      - 9000:9000
      - 9080:9080
    entrypoint: aca-py
    command: >
      start
        --auto-provision
        --webhook http://${ip_address}:8000/pharmacy
        --auto-respond-credential-proposal 
        --auto-respond-credential-offer 
        --auto-respond-credential-request
        --auto-verify-presentation 
        --inbound-transport http 0.0.0.0 9000 
        --inbound-transport ws 0.0.0.0 9001 
        --outbound-transport ws 
        --outbound-transport http 
        --genesis-file /var/lib/indy/my-net/pool_transactions_genesis 
        --log-level info
        --seed 000000000000000000000000000Agent
        --wallet-type indy 
        --wallet-key StewardWallet3 
        --wallet-name StewardWallet3
        --admin-insecure-mode 
        --admin 0.0.0.0 9080 
        -e http://${ip_address}:9000/ 
        -l Pharmacy
    volumes:
      - /Users/chef/MA/e-Prescriptions/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis
