#!/bin/bash

CONTAINER_RUNTIME="${CONTAINER_RUNTIME:-docker}"

$CONTAINER_RUNTIME build -t aries-cloudagent-run -f ./Dockerfile_doctor.run ./aries-cloudagent-python || exit 1

ARGS=""
for PORT in $PORTS; do
  ARGS="${ARGS} -p $PORT"
done

PTVSD_PORT="${PTVSD_PORT-5678}"

for arg in "$@"; do
  if [ "$arg" = "--debug" ]; then
    ENABLE_PTVSD=1
  fi
done
if [ -n "${ENABLE_PTVSD}" ]; then
  ARGS="${ARGS} -e ENABLE_PTVSD=\"${ENABLE_PTVSD}\" -p $PTVSD_PORT:$PTVSD_PORT"
fi

ARGS="${ARGS} -v $(pwd)/../logs:/home/indy/logs"

if [ -n "${WEBHOOK_URL}" ]; then
  ARGS="${ARGS} -e WEBHOOK_URL=\"${WEBHOOK_URL}\""
fi

if [ "$OSTYPE" == "msys" ]; then
  CONTAINER_RUNTIME="winpty docker"
fi

RAND_NAME=$(env LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w 16 | head -n 1)
$CONTAINER_RUNTIME run --rm -ti --network host -v $PWD/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis --name "aries-cloudagent-runner_${RAND_NAME}" \
    $ARGS aries-cloudagent-run "$@"
# $CONTAINER_RUNTIME run --rm -ti -v $PWD/pool_transactions_genesis:/var/lib/indy/my-net/pool_transactions_genesis -v /home/ubuntu/.indy_client:/home/indy/.indy_client --name "aries-cloudagent-runner_${RA>
#     $ARGS aries-cloudagent-run "$@"
