# Generated by Django 3.2.7 on 2021-10-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=120)),
                ('invitation_link', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_id', models.CharField(default='0000000000000', max_length=120, null=True)),
                ('firstname', models.CharField(default='Max', max_length=120, null=True)),
                ('lastname', models.CharField(default='Mustermann', max_length=120, null=True)),
                ('birthday', models.CharField(default='01.01.2000', max_length=120)),
                ('street', models.CharField(default='Musterstraße 1', max_length=120)),
                ('zip_code', models.CharField(default='123456', max_length=120)),
                ('city', models.CharField(default='Musterstraße', max_length=120)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('expiration_date', models.CharField(default='01.01.2022', max_length=120)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
