from django.db import connection, models

class Prescription(models.Model):
    id                  = models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    doctor_id           = models.CharField(max_length=120, null=True)
    doctor_fullname     = models.CharField(max_length=120, null=True)
    doctor_type         = models.CharField(max_length=120)
    doctor_phonenumber  = models.CharField(max_length=120)
    patient_insurance_id = models.CharField(max_length=50)
    patient_insurance_company =models.CharField(max_length=50)
    patient_fullname    = models.CharField(max_length=120, null=True)
    patient_birthday    = models.CharField(max_length=120)
    pharmaceutical      = models.CharField(max_length=120)
    number              = models.CharField(max_length=120, verbose_name="Quantity")
    extra_information   = models.CharField(max_length=1200)
    date_issued         = models.DateTimeField()
    contract_address    = models.CharField(max_length=120)
    prescription_id     = models.CharField(max_length=120)
    spending_key        = models.CharField(max_length=120)
    valid               = models.BooleanField(default=False)
    not_spent           = models.BooleanField(default=False, verbose_name="spendable")
    date_presented      = models.DateTimeField(auto_now_add=True)
    date_redeemed       = models.DateTimeField(blank=True, null=True)
    redeemed            = models.BooleanField(default=False)
    connection_id       = models.CharField(max_length=120)
    invoice             = models.BooleanField(default=False)
