# Generated by Django 3.2.7 on 2021-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_created',
            field=models.CharField(default='01.01.2000', max_length=120),
        ),
    ]
