# Generated by Django 3.2.7 on 2021-10-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='redemed',
            field=models.BooleanField(default=True),
        ),
    ]
