# Generated by Django 3.2.7 on 2021-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_prescription_redemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_redemed',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='redemed',
            field=models.BooleanField(default=False),
        ),
    ]
