# Generated by Django 3.2.7 on 2021-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20211004_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_redemed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
