# Generated by Django 3.2.7 on 2021-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_prescription_date_redemed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='date_redemed',
            new_name='date_redeemed',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='redemed',
            new_name='redeeme',
        ),
    ]
