# Generated by Django 3.2.7 on 2021-10-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20211004_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='redeeme',
            new_name='redeemed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='expiration',
        ),
    ]
