# Generated by Django 3.2.7 on 2021-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_auto_20211004_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='number',
            field=models.CharField(default='1', max_length=120, verbose_name='Quantity'),
        ),
    ]
