# Generated by Django 3.2.8 on 2021-10-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_prescription_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='not_spent',
            field=models.BooleanField(default=False, verbose_name='spendable'),
        ),
    ]
