# Generated by Django 3.2.7 on 2021-11-01 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_prescription_not_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_address',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='extra_information',
            field=models.CharField(default=django.utils.timezone.now, max_length=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_insurance_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_insurance_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='contract_address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_issued',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_fullname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor_type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='number',
            field=models.CharField(max_length=120, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_birthday',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_fullname',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmaceutical',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='spending_key',
            field=models.CharField(max_length=120),
        ),
    ]
