# Generated by Django 3.2.7 on 2021-11-01 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_auto_20211101_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='connection',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
