# Generated by Django 3.2.7 on 2021-11-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_prescription_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_issued',
            field=models.DateTimeField(),
        ),
    ]
