# Generated by Django 3.2.7 on 2021-10-22 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20211022_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='insurance_name',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='address',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='alias',
        ),
        migrations.AddField(
            model_name='connection',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='conection_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='insurance_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='zip_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
