# Generated by Django 3.2.7 on 2021-10-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20211022_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='conection_state',
            new_name='connection_state',
        ),
    ]
