# Generated by Django 4.0 on 2021-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_connection_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Check-in'),
        ),
    ]
